import React from "react";
import { ListGroup, Modal, Tab, Tabs } from "react-bootstrap";

import { FadeIn } from "@/common";

import styles from "./ApplicationInfoModal.module.css";

type ApplicationInfoModalProperties = {
    onClose: () => void;
    showApplicationInfoModal: boolean;
};

/**
 *
 * @param param0
 * @returns
 */
export const ApplicationInfoModal = ({
    onClose,
    showApplicationInfoModal,
}: ApplicationInfoModalProperties): JSX.Element => (
    <Modal
        contentClassName={styles.application_modal_content}
        onHide={onClose}
        show={showApplicationInfoModal}
    >
        <Modal.Header closeButton closeVariant="white">
            {"Buckles Chat Information"}
        </Modal.Header>
        <Modal.Body>
            <ListGroup variant="flush">
                <ListGroup.Item className={styles.application_modal_content}>
                    <ListGroup
                        className={styles.application_modal_listgroup_parent}
                    >
                        <Tabs
                            defaultActiveKey="specifications"
                            id="app_info_tabs"
                            justify
                            variant="pills"
                        >
                            <Tab
                                eventKey="specifications"
                                title="Specifications"
                            >
                                <FadeIn>
                                    <ListGroup.Item
                                        className={
                                            styles.application_modal_inner_listgroup_item
                                        }
                                    >
                                        <div>
                                            {"Front-End"}
                                            <ul>
                                                <FadeIn>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://nextjs.org/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"NextJS"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://react.dev/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"React"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://react-bootstrap.github.io/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"React-Bootstrap"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://react-hook-form.com/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"React Hook Form"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://swr.vercel.app/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"SWR"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://www.typescriptlang.org/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"Typescript"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://developer.mozilla.org/en-US/docs/Web/CSS"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"CSS"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://prettier.io/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"Prettier"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://eslint.org/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"ESLint"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://github.com/dimitropoulos/eslint-config-intense"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {
                                                                "Eslint-Config-Intense"
                                                            }
                                                        </a>
                                                    </li>
                                                </FadeIn>
                                            </ul>
                                        </div>
                                    </ListGroup.Item>
                                    <ListGroup.Item
                                        className={
                                            styles.application_modal_inner_listgroup_item
                                        }
                                    >
                                        <div>
                                            {"Back-End"}
                                            <ul>
                                                <FadeIn>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://expressjs.com/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"ExpressJS"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://www.postgresql.org/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"PostgreSQL"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://www.mongodb.com/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"MongoDB"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://redis.io/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"Redis"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://sequelize.org/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"Sequelize"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://jwt.io/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"JSON Web Tokens"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://sendgrid.com/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"Sendgrid"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://www.typescriptlang.org/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"Typescript"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://prettier.io/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"Prettier"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://eslint.org/"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {"ESLint"}
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a
                                                            className={
                                                                styles.application_modal_listgroup_link
                                                            }
                                                            href="https://github.com/dimitropoulos/eslint-config-intense"
                                                            rel="noreferrer"
                                                            target="_blank"
                                                        >
                                                            {
                                                                "Eslint-Config-Intense"
                                                            }
                                                        </a>
                                                    </li>
                                                </FadeIn>
                                            </ul>
                                        </div>
                                    </ListGroup.Item>
                                </FadeIn>
                            </Tab>
                            <Tab
                                eventKey="author"
                                tabClassName="btn btn-outline-secondary"
                                title="Author"
                            >
                                <FadeIn>
                                    <ListGroup.Item
                                        className={
                                            styles.application_modal_inner_listgroup_item
                                        }
                                    >
                                        <div
                                            className={
                                                styles.application_modal_information_author
                                            }
                                        >
                                            <div
                                                className={
                                                    styles.application_modal_information_author_header
                                                }
                                            >
                                                {"Cameron Thacker"}
                                                <a
                                                    className={
                                                        styles.application_modal_listgroup_link
                                                    }
                                                    href="https://github.com/cthacker-udel"
                                                    rel="noreferrer"
                                                    target="_blank"
                                                >
                                                    <i className="fa-brands fa-github" />
                                                </a>
                                                <a
                                                    className={
                                                        styles.application_modal_listgroup_link
                                                    }
                                                    href="https://www.linkedin.com/in/cameron-thacker/"
                                                    rel="noreferrer"
                                                    target="_blank"
                                                >
                                                    <i className="fa-brands fa-linkedin" />
                                                </a>
                                                <a
                                                    className={
                                                        styles.application_modal_listgroup_link
                                                    }
                                                    href="https://cthacker.vercel.app/"
                                                    rel="noreferrer"
                                                    target="_blank"
                                                >
                                                    <i className="fa-solid fa-newspaper" />
                                                </a>
                                            </div>
                                            <span
                                                className={
                                                    styles.application_modal_information_author_description
                                                }
                                            >
                                                {
                                                    "I created this application to test my limits of front-end development. See how far I could push the limits until it became unfathomable to complete. I learned that was a fool's game, anything I put my mind to, with enough determination, it was completed. I know that sounds cliche, but when you have the necessary drive, anything is possible. I took a month off of creating react apps to pivot to machine learning, and decided to give myself a challenge as a welcome back. I think I achieved a good result with this. I've been doing full stack development for quite some time now, whether that be making the backend in C#, JS, or TS. I've learned the concepts of how to manage and implement an local API to handle requests from your application. The codebase is extremely high quality, with extensive documentation and structurally sound. This has been one of my top projects recently, and I am glad to share this with you. I dedicated this website to one of my pets, my pet cat Buckles, she was raised from the wild and is an amazing, loving cat. "
                                                }
                                                <i className="fa-solid fa-paw" />
                                            </span>
                                        </div>
                                    </ListGroup.Item>
                                </FadeIn>
                            </Tab>
                        </Tabs>
                    </ListGroup>
                </ListGroup.Item>
            </ListGroup>
        </Modal.Body>
    </Modal>
);
